version: 1.0.{build}

image: 
  - Visual Studio 2017
  - Ubuntu

platform: 
  - x64

environment:
    matrix:
      - nodejs_version: 16
      - nodejs_version: 14
      - nodejs_version: 12
     
test_script:
  - ps: Write-Host "msnodesqlv8 test script"    
for:
  -
      matrix:
        only:
          - image: Visual Studio 2017
    
      clone_folder: c:\projects\node_modules\msnodesqlv8

      before_test:
        - cmd: sc config sqlbrowser start= auto
        - cmd: net start sqlbrowser

      install:
        - ps: Install-Product node $env:nodejs_version $env:platform
        - npm install
        - ps: Write-Host "Installing ODBC driver..." -ForegroundColor Cyan
        - ps: Write-Host "Downloading..."
        - ps: $msiPath = "$($env:USERPROFILE)\msodbcsql.msi"
        - ps: (New-Object Net.WebClient).DownloadFile('https://www.microsoft.com/en-us/download/confirmation.aspx?id=56567&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1', $msiPath)
        - ps: Write-Host "Installing..."
        - ps: Write-Host $msiPath
        - cmd: cmd /c start /wait msiexec /i "$msiPath" /q
    
      build_script:
        - cmd: node --version

      test_script:
        - ps: Get-OdbcDriver
        - cmd: tool\appveyor-win.cmd
  -        
      matrix:
        only:
          - image: Ubuntu
          - platform: x64

      services:
        - mssql

      clone_folder: /home/appveyor/projects/node_modules/msnodesqlv8 
      
      test_script:
        - sh: "sleep 2"
        - sh: "./node_modules/.bin/env-cmd -e appv-ubuntu ./node_modules/.bin/mocha 2>&1"

      install:
        - nvm install $nodejs_version
        - npm install
