version: 1.0.{build}

image: 
  - Visual Studio 2015
  - Ubuntu

platform: 
  - x64

environment:
    matrix:
      - nodejs_version: 8
      - nodejs_version: 14
      - nodejs_version: 13
      - nodejs_version: 12
      - nodejs_version: 11
      - nodejs_version: 10
     
test_script:
  - ps: Write-Host "msnodesqlv8 test script"    
for:
  -
      matrix:
        only:
          - image: Visual Studio 2015
    
      clone_folder: c:\projects\node_modules\msnodesqlv8

      before_test:
        - cmd: sc config sqlbrowser start= auto
        - cmd: net start sqlbrowser

      install:
        - ps: Install-Product node $env:nodejs_version $env:platform
        - npm install

      build_script:
        - cmd: node --version

      test_script:
        - cmd: tool\appveyor-win.cmd
  -        
      matrix:
        only:
          - image: Ubuntu
          - platform: x64

      services:
        - mssql

      clone_folder: /home/appveyor/projects/node_modules/msnodesqlv8 
      
      test_script:
        - sh: "node runtest -x -t connection-pool -t pause -t concurrent -t multiple-errors -t geography -t tvp -t warnings.js -t compoundqueries.js -t querycancel.js -t txn.js -t datatypes.js -t params.js -t query.js -t querytimeout.js -t connect.js -t bulk.js -t sproc.js -t prepared.js -t userbind.js -t dates.js 2>&1"

      install:
        - nvm install $nodejs_version
        - npm install
