version: 1.0.{build}

image: 
  - Ubuntu
  - Visual Studio 2015

platform:
  - x86
  - x64

environment:
      matrix:
        - nodejs_version: "14"
        - nodejs_version: "13"
        - nodejs_version: "12"
        - nodejs_version: "11"
        - nodejs_version: "10"
test_script:
  - ps: Write-Host "msnodesqlv8 test script"    
matrix:
  - fast_finish: true
for:
  -
      matrix:
        only:
          - image: Visual Studio 2015
    
      clone_folder: c:\projects\node_modules\msnodesqlv8

      before_test:
        - cmd: sc config sqlbrowser start= auto
        - cmd: net start sqlbrowser

      install:
        - ps: Install-Product node $env:nodejs_version $env:platform
        - npm install

      build_script:
        - cmd: node --version

      test_script:
        - cmd: tool\appveyor-win.cmd

      matrix:
        only:
          - image: Ubuntu
        except:
          - platform: x86

      services:
        - mssql

      clone_folder: /home/appveyor/projects/node_modules/msnodesqlv8 
      
      install:
        - ps: Install-Product node $env:nodejs_version $env:platform
        - npm install
